# Generated by Django 3.2.8 on 2021-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_alter_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
