# Generated by Django 3.2.8 on 2021-10-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0003_alter_content_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Profiles',
        ),
    ]
